version: '3.5'

services:
  postgres_freelance:
    container_name: postgres_freelance
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-SecretPassword(!)}
      PGDATA: /data/postgres
    volumes:
      - postgres_freelance:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres_freelance
    restart: unless-stopped

  pgadmin_freelance:
    container_name: pgadmin_freelance
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_freelance:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres_freelance
    restart: unless-stopped

  freelance_back:
    container_name: freelance_back
    environment:
      DB_CONNECT: ${DB_CONNECT:-jdbc:postgresql://postgres_freelance/postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-SecretPassword(!)}
    image: postgres_freelance
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "9000:9000"
    networks:
      - postgres_freelance
    depends_on:
      - postgres_freelance


networks:
  freelance_back:
    driver: bridge
  postgres_freelance:
    driver: bridge

volumes:
  postgres_freelance:
  pgadmin_freelance:
  freelance_back:
